ldapjs/node-ldapjs

CHANGES.md, lib/dn.js, lib/server.js, test/dn.test.js
Certain applications depend upon DN string formatting in a manner more
strict that specified in the RFC.  To enable format transcription and
reproduction, some changes were made to how DNs are converted to/from
strings.
- Store RDN strings raw instead of escaped
- Record formatting details during DN/RDN parsing
- Add DN.format method to control format recreation
- Remove DN.spaced method in favor of DN.setFormat
Fix mcavage/node-ldapjs#176
=> Overhaul DN parsing and formatting

docs/client.md, docs/server.md, lib/client/index.js, lib/index.js, package.json, test/client.test.js, test/messages/del_request.test.js, test/messages/parser.test.js, test/server.test.js
This PR removes the explicit dependency on Bunyan. It replaces the internal usage of Bunyan with a no operation logger, `abstract-logging`. This removes the overhead introduced by Bunyan when an external logger is not supplied. Bunyan is not a fast logger, and thus slows down the `ldapjs` library unnecessarily (see https://github.com/pinojs/pino#benchmarks).
The documentation is also updated with some detail on what is required of a passed in logger and points out a couple compatible loggers.
=> Remove dependency on Bunyan

README.md, package.json
See #399 and #286 for discussion.
It's pretty clear that dtrace dependency is causing too many problems for its own good. Searching for `dtrace` issues on this repository brings up plenty of issues.
=> Remove dtrace-provider from optionalDependencies

lib/change.js, test/client.test.js
Now the change/modification value can be set to `undefined` or `null`, in order to indicate a non multi-valued attribute. As result `changes[0]._modification._vals` in `return this._send(req, [errors.LDAP_SUCCESS], null, callback)` (see [client.js#672][1]) is an empty array. The request is accepted by the LDAP-server (OpenLDAP) and the attribute is deleted.
To execute this operation use the following template (replace *attributeName* by the real name):
let change = { operation : 'delete', modification: { attributeName : undefined }};
client.modify(dn, change, (err, res) => { ... });
[1]: https://github.com/mcavage/node-ldapjs/blob/master/lib/client/client.js#L672
=> Fixing issue #434 (can delete attributes)

lib/client/client.js, test/client.test.js
With a client, when using bindDN and bindCredentials, if the credentials are bad then the bind fails as expected -- but the socket is left open. An explicit call to `client.destroy()` is required in order to release the socket. This is confusing since the socket would be closed after a successful operation. Closing the socket upon bind failure makes it consistent.
Also, the bind error was being reported twice. Once as an emit, and again in the callback. Because a bind failure ends with the callback being executed, an emit doesn't make sense.
The test that applies to this behavior is *auto-bind bad credentials* in `test/client.test.js` -- it continues to pass with the changes I've made, but because it calls `clt.destroy()` explicitly, it doesn't replicate the problems I was having.
=> destroy socket if auto-bind fails

.taprc, lib/client/client.js, lib/client/request-queue/enqueue.js, lib/client/request-queue/flush.js, lib/client/request-queue/index.js, lib/client/request-queue/purge.js, package.json, test/lib/client/request-queue/enqueue.test.js, test/lib/client/request-queue/flush.test.js, test/lib/client/request-queue/purge.test.js
This is basically a step 1 in trying to make the code base a little easier to maintain and test.
Also, moves the test file glob into `.taprc` because `test/**/*.test.js` was not doing a full recursive expansion of all test directories. This is why `'test/**/*.test.js'` was necessary.
=> Refactor client RequestQueue into testable module

README.md
These instructions do not jive with my reading comprehension -- https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
This PR _should_ fix the build status badge once `next` goes to `master`.
=> Actually fix the badge

lib/filters/index.js, test/filters/parse.test.js
fixes [escapedToHex](https://github.com/ldapjs/node-ldapjs/blob/a113953e0d91211eb945d2a3952c84b7af6de41c/lib/filters/index.js#L167) when two escaped characters are next to each other
```js
escapedToHex("\\(\\)")
// before fix: "\\28\\)"
//  after fix: "\\28\\29"
```
=> Fix escapedToHex

lib/client/client.js, test/client.test.js
This pull request rebases the work from https://github.com/ldapjs/node-ldapjs/pull/433 to the next branch. It also adds tests to the two cases concerned by the PR:
- connection refused (LDAP server not started)
- connection timeout (firewall problem)
I took this as a opportunity to dive deeper into the code to understand what was actually causing the error to be thrown, I hope the code is a little cleaner than a blind handling of all errors (which caused other tests to fail). The issue was a poor handling of connection errors in the bind method. Since it's the first async method, it is the one that should report connection issues to the server, which it did not. Another issue was the handling of connection refused errors that caused a general error in ldapjs. Sending the exception to the …
=> Handle connection refused and connection timeouts gracefully

lib/client/client.js, lib/corked_emitter.js, test/client.test.js, test/corked_emitter.test.js
This PR replaces the normal EventEmitter that's returned from `Client.search()` with a compatible "corked" version that will not start emitting events until a listener appears. It eliminates a race condition where some early events could be missed, preventing the user of the method from seeing the first few search results or, in extreme cases, the end boundary of the search.
For #602
=> Implement queueing search events until a listener appears

lib/messages/search_request.js, test/messages/search_request.test.js
This change fixes how DNs are serialized into BER for SearchRequest messages.
It drops spaces around commas, since it breaks some LDAP servers that expect
the DN to be separated by comma only as per RFC 4514. The old format of
spaced separators from LDAPv2 is thus no longer used.
For #611
=> Remove spaces from DNs in SearchRequest

package.json, test/client.test.js
This fixes a test failure when the host has something listening
on the LDAP TCP port. Previously, the test cases would assume
that the port was free and they would not connect.
For #612
=> Use a random TCP port for testing timeouts/rejects

.github/workflows/main.yml
Trying to resolve https://github.com/coverallsapp/github-action/issues/26
Also a couple other updates.
=> Update main CI

lib/filters/filter.js
This fixes #629 where, if this package was used in 2 instances (e.g. depended upon by 2 different packages) where one passes a Client object to the other, they would not recognize each other's `BerWriter` instances and throw an error on `.search()` with filters.
=> Replace instanceof check with duck-typing in Filter#toBer mixin

lib/messages/search_entry.js, test/client.test.js, test/messages/search_entry.test.js, test/server.test.js
This PR addresses issue #645
This change fixes how DNs are serialised into BER for searchResEntry messages, and is related to the following other issues and PRs (#611, #613).
The change is required as it breaks clients that are expecting the reply to be comma separated only and not comma space `, `
=> Remove spaces in searchResEntry objectName

docs/client.md, lib/client/client.js, lib/client/index.js, test/client.test.js
Resolves: https://github.com/ldapjs/node-ldapjs/issues/408
=> Client support multiple servers

docs/client.md
Fix spelling error on `docs/client.md`
The #del <whatever> previously has an argument `callbak`.
I believe it was a typo and have corrected that to `callback`.
=> [Docs] Improved documentation

lib/client/client.js, lib/messages/message.js, lib/messages/result.js, lib/messages/search_response.js, lib/server.js
To address issue #676 .
Use of log methods (e.g. `log.trace()`) in conditional tests prior to actually logging messages yields undesirable behavior when using Pino as an alternative to Bunyan (and potentially other Bunyan-like packages).
1. Pino methods have void return values and always fail the conditional test
2. Pino method calls with no parameters still produce a logging event with several default values but no message field
Additionally, the default behavior for Bunyan and similar loggers is to filter events based on instance config options. The conditionals are not necessary.
=> Remove use of logging methods in conditional tests

lib/messages/search_response.js
In commit c6fa25985b078ce0ba27da50d1d8676d3e18fe30, "var" usage
was replaced with const. The code previously worked because "var"
has function scoping unlike const which has block scoping.
TypeError: Cannot read property 'attributes' of null
=> Fix crash in res.send()

docs/client.md, lib/client/client.js, lib/errors/index.js, test/client.test.js
Emit error event if other error events are not listened to.
Currently if someone wants to catch client errors they have to subscribe to multiple error events
```js
client.on("error", (err) => {
assert.ifError(err);
});
client.on("setupError", (err) => {
assert.ifError(err);
});
client.on("connectError", (err) => {
assert.ifError(err);
});
client.on("connectTimeout", (err) => {
assert.ifError(err);
});
client.on("connectRefused", (err) => {
assert.ifError(err);
});
```
This PR will allow them to just subscribe to the `error` event to catch all of them but still allow them to subscribe to more if they want to.
=> Emit error event if other error events are not listened to

lib/client/client.js, lib/client/search_pager.js, test/client.test.js
This fixes the same problems for paged searches as does
https://github.com/ldapjs/node-ldapjs/pull/610 for unpaged searches.
By passing an EventEmitter via callback there exist cases when events
are emitted before listeners are registered, resulting in missed
events.
The Change turns SearchPager into a CorkedEmitter which is already
used as a solution for non paged searches. Doing so requires the
internal 'search' event to be dropped.
This change adapts a test case originally by László Szűcs (@ifroz).
Signed-off-by: Philippe Seewer <philippe.seewer@bfh.ch>
=> SearchPager: Implement queueing events until a listener appears

docs/examples.md, examples/cluster-threading-net-server.js, examples/cluster-threading.js, lib/server.js, test/server.test.js
connection router hook added to accommodate multithreaded servers
e.g. passing `options.connectionRouter(connection)` will allow for:
function connectionRouter(connection) {
sendToThread(findRoute(connection), connection);
}
function sendToThread(threadId, connection) {
...wrap in packet for IPC and send to thread...
}
function threadMessage(message) {
notListeningServerOnChildThread.newConnection(message.connection);
}
in order to preserve extant functionality while adding multi-threading support.
=> connection router to accomodate multithreading

lib/messages/moddn_request.js, test/client.test.js
=> fix: modifyDn length fix

lib/client/client.js, test/client.test.js
Fixed while getting AD thumbnailPhoto to work.
To repro, add a thumbnailPhoto to AD.
Note: I don't believe I ever reported this problem, but I've been using the fix for a long time.
=> fix: client.add not adding buffers properly

lib/server.js, test/server.test.js
Ensuring a connection in an anonymous state has a consistent bindDN variable, regardless of being implicit, or explicitly bound.
Added hook to switch to anonymous on unbind too.
Server should close such connections but added as a safeguard to ensure permissions are dropped regardless of connection termination state.
https://github.com/ldapjs/node-ldapjs/issues/748
=> Server - Consistent BindDN

docs/client.md
Some people (including myself) attempt to use the LDAP client without registering a handler to the _error_ event, since e.g. connection errors are supposed to be included in the callbacks of other methods. Since the client is an `EventEmitter` however the Node.js process will exit if the handler is missing.
This PR adds a note to the documentation to avoid confusion as suggested in #356 and #498.
=> Add Note on Client Error Handling to Documentation

lib/client/client.js, test/client.test.js
This will force destroy a socket after calling destroy. 
Fixing the file descriptor leak issue, see https://github.com/ldapjs/node-ldapjs/issues/605
=> force socket to be closed on destroy

.github/workflows/integration.yml, docker-compose.yml, package.json
GitHub fixed the reason we needed hacks https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry
=> Update docker config

.github/workflows/main.yml, .taprc, .taprc.yml
This codebase is not well covered to begin with. Plus, we can simply fail from thresholds. Eventually, we should be able to use thresholds of 100% and tools like Coveralls would be completely pointless.
=> Remove coveralls

lib/server.js, test/server.test.js
=> Progress on supporting IPv6

lib/filters/and_filter.js, lib/filters/approx_filter.js, lib/filters/equality_filter.js, lib/filters/ext_filter.js, lib/filters/ge_filter.js, lib/filters/index.js, lib/filters/le_filter.js, lib/filters/not_filter.js, lib/filters/or_filter.js, lib/filters/presence_filter.js, lib/filters/substr_filter.js, package.json
As titled. This will replace the `node-filter` package with the `@ldapjs/filter` package. I'm going to leave it as the `-rc.` release for this PR since it's merging into the `next` branch. I suspect I will end up doing a lot more work in `@ldapjs/filter` as I start working on `@ldapjs/messages`.
=> Replace node-filter (resolves #622)

docs/client.md
When the connection fails, e.g. due to a faulty dns lookup, the `connectError` event is emitted, not `error`.
https://github.com/ldapjs/node-ldapjs/blob/master/lib/client/client.js#L806-L815
The documentation however says to listen on `error` to catch these events.
```js
client.on('error', (err) => {
// handle connection error
})
```
Not sure if this is an error in documentation or the wrong event is used to emit an error. This PR just updates the documentation.
=> Document correct connection error in client documentation

docs/client.md
Just a minor fix, I'm guessing there is a more correct way to access the attributes.
=> Quick fix for outdated client doc still referring to result.object

package.json, test/issue-845.test.js
This issue resolves issue #845 by updating `@ldapjs/messages` to the latest version and adding a test that shows how the module should be used to evaluate search request scopes.
=> Resolve issue #845

lib/server.js, test/server.test.js
In case the supplied function goes into a different context (using vm.SourceTextModule for example) the "instanceof" checks fail.
typeof obj === 'function' and Array.isArray are true among contexts. 
BTW: as far I read isArray has explicitly been created for cross-realm situations.
=> transcontextual safe type checks

lib/client/client.js, test/issue-890.test.js
=> Address crash for unmatched server responses

.github/workflows/integration.yml, docker-compose.yml, package.json, test-integration/client/issue-923.test.js
Additionally sets integration tests to use the prior Docker image until #924 can be resolved with a newer image.
=> Add integration test for issue #923

lib/server.js, test/server.test.js
req.dn used to be parsed, now it's a string. This causes the server to crash because the assertion error cannot be trapped
=> server: prevent crash on blank DN bind
